//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.mastersign.odec.cli {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("de.mastersign.odec.cli.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The certificate file was not found. ähnelt.
        /// </summary>
        internal static string CertificateFileNotFound {
            get {
                return ResourceManager.GetString("CertificateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;descriptions&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;!-- The element for the owner description. --&gt;
        ///  &lt;xs:element name=&quot;Owner&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;Institute&quot; type=&quot;xs:string&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot; /&gt;
        ///        &lt;xs:element name=&quot;Operator&quot; type=&quot;xs:string&quot; minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot; /&gt;
        ///        &lt;xs:element name=&quot;Role&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot; maxOccu [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string DescriptionSchema {
            get {
                return ResourceManager.GetString("DescriptionSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while copying storage file &apos;{0}&apos;:
        ///{1} ähnelt.
        /// </summary>
        internal static string Error_CopyingStorageFile {
            get {
                return ResourceManager.GetString("Error_CopyingStorageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while creating new entity.
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_CreatingEntity {
            get {
                return ResourceManager.GetString("Error_CreatingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while creating the target container:
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_CreatingTargetContainer {
            get {
                return ResourceManager.GetString("Error_CreatingTargetContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while initializing the container:
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_InitializingContainer {
            get {
                return ResourceManager.GetString("Error_InitializingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of provenance parameter set is empty. ähnelt.
        /// </summary>
        internal static string Error_NameOfProvenanceParameterSetIsEmpty {
            get {
                return ResourceManager.GetString("Error_NameOfProvenanceParameterSetIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of entity value is empty. ähnelt.
        /// </summary>
        internal static string Error_NameOfValueIsEmpty {
            get {
                return ResourceManager.GetString("Error_NameOfValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while opening the source container:
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_OpeningSourceContainer {
            get {
                return ResourceManager.GetString("Error_OpeningSourceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given profile &apos;{0}&apos; does not match the container profile &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Error_ProfileMismatch {
            get {
                return ResourceManager.GetString("Error_ProfileMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given profile version &apos;{0} does not match the container profile version &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Error_ProfileVersionMismatch {
            get {
                return ResourceManager.GetString("Error_ProfileVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given provenance parameter set source file does not exist.
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_ProvenanceParameterSetSourceFileNotFound {
            get {
                return ResourceManager.GetString("Error_ProvenanceParameterSetSourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while reading certificate:
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_ReadingCertificate {
            get {
                return ResourceManager.GetString("Error_ReadingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while reading private key:
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_ReadingPrivateKey {
            get {
                return ResourceManager.GetString("Error_ReadingPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while sealing the container:
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_SealingContainer {
            get {
                return ResourceManager.GetString("Error_SealingContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while storing a new entity.
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_StoringEntity {
            get {
                return ResourceManager.GetString("Error_StoringEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error while reinstating history edition. ähnelt.
        /// </summary>
        internal static string Error_UnexpectedReinstateError {
            get {
                return ResourceManager.GetString("Error_UnexpectedReinstateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation step 1 failed. Container structure is invalid. ähnelt.
        /// </summary>
        internal static string Error_ValidationStep1Failed {
            get {
                return ResourceManager.GetString("Error_ValidationStep1Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation step 2 failed. Value integrity damaged. ähnelt.
        /// </summary>
        internal static string Error_ValidationStep2Failed {
            get {
                return ResourceManager.GetString("Error_ValidationStep2Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation step 3 failed. Owner certificate invalid. ähnelt.
        /// </summary>
        internal static string Error_ValidationStep3Failed {
            get {
                return ResourceManager.GetString("Error_ValidationStep3Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation step 4 failed. Container is not conform to profile. ähnelt.
        /// </summary>
        internal static string Error_ValidationStep4Failed {
            get {
                return ResourceManager.GetString("Error_ValidationStep4Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given entity value source file does not exist.
        ///{0} ähnelt.
        /// </summary>
        internal static string Error_ValueSourceFileNotFound {
            get {
                return ResourceManager.GetString("Error_ValueSourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password:  ähnelt.
        /// </summary>
        internal static string PasswordSource_GetPassword_Prompt {
            get {
                return ResourceManager.GetString("PasswordSource_GetPassword_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key file was not found. ähnelt.
        /// </summary>
        internal static string PrivateKeyNotFound {
            get {
                return ResourceManager.GetString("PrivateKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The choosen storage type is not supported. ähnelt.
        /// </summary>
        internal static string StorageTypeNotSupported {
            get {
                return ResourceManager.GetString("StorageTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given container was not found:
        ///{0} ähnelt.
        /// </summary>
        internal static string Warning_ConatinerNotFound {
            get {
                return ResourceManager.GetString("Warning_ConatinerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given container allready exists:
        ///{0} ähnelt.
        /// </summary>
        internal static string Warning_ContainerAllreadyExists {
            get {
                return ResourceManager.GetString("Warning_ContainerAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given edition ID was not found in the container history. ähnelt.
        /// </summary>
        internal static string Warning_EditionIdNotFound {
            get {
                return ResourceManager.GetString("Warning_EditionIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file does not exists:
        ///{0} ähnelt.
        /// </summary>
        internal static string Warning_FileNotFound {
            get {
                return ResourceManager.GetString("Warning_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In place transformation is not supported. ähnelt.
        /// </summary>
        internal static string Warning_InPlaceTransformationNotSupported {
            get {
                return ResourceManager.GetString("Warning_InPlaceTransformationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given value for the argument &apos;-mode, -m &lt;working mode&gt;&apos; is invalid. ähnelt.
        /// </summary>
        internal static string Warning_InvalidMode {
            get {
                return ResourceManager.GetString("Warning_InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given value for the argument &apos;-storage, -s &lt;storage type&gt;&apos; is invalid. ähnelt.
        /// </summary>
        internal static string Warning_InvalidStorageType {
            get {
                return ResourceManager.GetString("Warning_InvalidStorageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No container path given. Use &apos;-c &lt;file/dir&gt;&apos;. ähnelt.
        /// </summary>
        internal static string Warning_NoContainerPathGiven {
            get {
                return ResourceManager.GetString("Warning_NoContainerPathGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No entity descriptions given. Use &apos;-e &lt;desciption file&gt;&apos;. ähnelt.
        /// </summary>
        internal static string Warning_NoEntityDescriptionFile {
            get {
                return ResourceManager.GetString("Warning_NoEntityDescriptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No owner description file given. Use &apos;-o &lt;owner file&gt;&apos;. ähnelt.
        /// </summary>
        internal static string Warning_NoOwnerDescriptionFile {
            get {
                return ResourceManager.GetString("Warning_NoOwnerDescriptionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No profile file given. Use &apos;-p &lt;profile file&gt;&apos;. ähnelt.
        /// </summary>
        internal static string Warning_NoProfileFile {
            get {
                return ResourceManager.GetString("Warning_NoProfileFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No target path given. Use &apos;-t &lt;target file/dir&gt;&apos;. ähnelt.
        /// </summary>
        internal static string Warning_NoTargetPath {
            get {
                return ResourceManager.GetString("Warning_NoTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No valid target edition ID given. ähnelt.
        /// </summary>
        internal static string Warning_NoValidTargetEditionId {
            get {
                return ResourceManager.GetString("Warning_NoValidTargetEditionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given path was not found:
        ///{0} ähnelt.
        /// </summary>
        internal static string Warning_PathNotFound {
            get {
                return ResourceManager.GetString("Warning_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reinstating the given edition as current edition is not possible. ähnelt.
        /// </summary>
        internal static string Warning_ReinstatingImpossible {
            get {
                return ResourceManager.GetString("Warning_ReinstatingImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given target storage type is not supported. ähnelt.
        /// </summary>
        internal static string Warning_StorageTypeNotSupported {
            get {
                return ResourceManager.GetString("Warning_StorageTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given target path allready exists:
        ///{0} ähnelt.
        /// </summary>
        internal static string Warning_TargetPathAllreadyExists {
            get {
                return ResourceManager.GetString("Warning_TargetPathAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access denied for reading the XML file &apos;{0}&apos;:
        ///	{1} ähnelt.
        /// </summary>
        internal static string XML_FileAccessDenied {
            get {
                return ResourceManager.GetString("XML_FileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The XML file &apos;{0}&apos; was not found:
        ///	{1} ähnelt.
        /// </summary>
        internal static string XML_FileNotFound {
            get {
                return ResourceManager.GetString("XML_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while parsing the XML file &apos;{0}&apos;:
        ///	{1} ähnelt.
        /// </summary>
        internal static string XML_ParsingError {
            get {
                return ResourceManager.GetString("XML_ParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while reading the XML file &apos;{0}&apos;:
        ///	{1} ähnelt.
        /// </summary>
        internal static string XML_ReadingError {
            get {
                return ResourceManager.GetString("XML_ReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The XML file &apos;{0}&apos; does not contain the expected root element &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string XML_UnexpectedRootElement {
            get {
                return ResourceManager.GetString("XML_UnexpectedRootElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while validation of XML file &apos;{0}&apos;:{1}{2} ähnelt.
        /// </summary>
        internal static string XML_ValidationError {
            get {
                return ResourceManager.GetString("XML_ValidationError", resourceCulture);
            }
        }
    }
}
