//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.mastersign.odec.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("de.mastersign.odec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given string is empty. ähnelt.
        /// </summary>
        internal static string ArgumentException_EmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The XML transformation into canonical representation does not support Stream as output. ähnelt.
        /// </summary>
        internal static string BclC14NCanonicalizer_Canonize_NotSupported_StreamAsOutput {
            get {
                return ResourceManager.GetString("BclC14NCanonicalizer_Canonize_NotSupported_StreamAsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The XML transformation into canonical representation does not support XmlDocument as input. ähnelt.
        /// </summary>
        internal static string BclC14NCanonicalizer_Canonize_NotSupported_XmlDocumentAsInput {
            get {
                return ResourceManager.GetString("BclC14NCanonicalizer_Canonize_NotSupported_XmlDocumentAsInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Given type not found in the text. ähnelt.
        /// </summary>
        internal static string BclKeyHelper_DecodePem_ArgumentException_TypeNotFound {
            get {
                return ResourceManager.GetString("BclKeyHelper_DecodePem_ArgumentException_TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while parsing private key. ähnelt.
        /// </summary>
        internal static string BclKeyHelper_DecodeRSAPrivateKey_FormatException_ErrorParsingPrivateKey {
            get {
                return ResourceManager.GetString("BclKeyHelper_DecodeRSAPrivateKey_FormatException_ErrorParsingPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given text does not contain PEM encoded data with the id &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string BouncyCastleKeyHelper_ExtractPem_NoPemData {
            get {
                return ResourceManager.GetString("BouncyCastleKeyHelper_ExtractPem_NoPemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signature of the certificate is invalid: {0}
        ///{1} ähnelt.
        /// </summary>
        internal static string BouncyCastleRSAProvider_CheckCertificateSignature_Failed {
            get {
                return ResourceManager.GetString("BouncyCastleRSAProvider_CheckCertificateSignature_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The signature of the certificate is valid: {0} ähnelt.
        /// </summary>
        internal static string BouncyCastleRSAProvider_CheckCertificateSignature_Success {
            get {
                return ResourceManager.GetString("BouncyCastleRSAProvider_CheckCertificateSignature_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trusted certification authority found {0} ähnelt.
        /// </summary>
        internal static string BouncyCastleRSAProvider_ValidateCertificate_CAFound {
            get {
                return ResourceManager.GetString("BouncyCastleRSAProvider_ValidateCertificate_CAFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No trusted certification authority found for {0} ähnelt.
        /// </summary>
        internal static string BouncyCastleRSAProvider_ValidateCertificate_NoCAFound {
            get {
                return ResourceManager.GetString("BouncyCastleRSAProvider_ValidateCertificate_NoCAFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The certificate is self signed but the validation rules does not allow self signed certificates. ähnelt.
        /// </summary>
        internal static string BouncyCastleRSAProvider_ValidateCertificate_NoSelfSignedCertsAllowed {
            get {
                return ResourceManager.GetString("BouncyCastleRSAProvider_ValidateCertificate_NoSelfSignedCertsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The certificate ist valid and trusted: {0} ähnelt.
        /// </summary>
        internal static string BouncyCastleRSAProvider_ValidateCertificate_Success {
            get {
                return ResourceManager.GetString("BouncyCastleRSAProvider_ValidateCertificate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given array has more than one dimension. ähnelt.
        /// </summary>
        internal static string CatalogBase_CopyTo_ArgumentException_MoreThanOneDimension {
            get {
                return ResourceManager.GetString("CatalogBase_CopyTo_ArgumentException_MoreThanOneDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is not enough space in the array for all items of the catalog. ähnelt.
        /// </summary>
        internal static string CatalogBase_CopyTo_ArgumentException_NotEnoughSpace {
            get {
                return ResourceManager.GetString("CatalogBase_CopyTo_ArgumentException_NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The GUID in the given XML element is not valid. ähnelt.
        /// </summary>
        internal static string CatalogItem_LoadFromXml_FormatException_InvalidGuid {
            get {
                return ResourceManager.GetString("CatalogItem_LoadFromXml_FormatException_InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given RSA provider is not a certificate. ähnelt.
        /// </summary>
        internal static string CertificationAuthorityDirectory_GetSigningCertificate_NoCertificate {
            get {
                return ResourceManager.GetString("CertificationAuthorityDirectory_GetSigningCertificate_NoCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string CompatibilityFlags_None {
            get {
                return ResourceManager.GetString("CompatibilityFlags_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die supress structure XML canonicalization ähnelt.
        /// </summary>
        internal static string CompatibilityFlags_SupressStructureXMLCanonicalization {
            get {
                return ResourceManager.GetString("CompatibilityFlags_SupressStructureXMLCanonicalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die write signature canonicalized ähnelt.
        /// </summary>
        internal static string CompatibilityFlags_WriteXmlSignatureCanonicalized {
            get {
                return ResourceManager.GetString("CompatibilityFlags_WriteXmlSignatureCanonicalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified entity does not exist. ähnelt.
        /// </summary>
        internal static string Container_ArgumentException_EntityDoesNotExist {
            get {
                return ResourceManager.GetString("Container_ArgumentException_EntityDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given label was not found in the index. ähnelt.
        /// </summary>
        internal static string Container_ArgumentNullException_LabelNotFound {
            get {
                return ResourceManager.GetString("Container_ArgumentNullException_LabelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given ID was not found in the history. ähnelt.
        /// </summary>
        internal static string Container_CanReinstateHistoryEdition_ArgumentException_EditionNotFound {
            get {
                return ResourceManager.GetString("Container_CanReinstateHistoryEdition_ArgumentException_EditionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The container must be in the process phase &apos;Sealed&apos; to allow this operation. ähnelt.
        /// </summary>
        internal static string Container_CanReinstateHistoryEdition_InvalidOperation_WrongPhase {
            get {
                return ResourceManager.GetString("Container_CanReinstateHistoryEdition_InvalidOperation_WrongPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A following edition has removed an entity that is needed to reinstate the specified edition. ähnelt.
        /// </summary>
        internal static string Container_CanReinstateHistoryEdition_Reason_EntityRemoved {
            get {
                return ResourceManager.GetString("Container_CanReinstateHistoryEdition_Reason_EntityRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The salt of the specified edition was removed to prevent reinstating it as current edition. ähnelt.
        /// </summary>
        internal static string Container_CanReinstateHistoryEdition_Reason_SaltRemoved {
            get {
                return ResourceManager.GetString("Container_CanReinstateHistoryEdition_Reason_SaltRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The container needs at least one entity. ähnelt.
        /// </summary>
        internal static string Container_FinishInitialization_InvalidOperation_NoEntity {
            get {
                return ResourceManager.GetString("Container_FinishInitialization_InvalidOperation_NoEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Container history &apos;{0}&apos; found. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_ContainerHistoryFound {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_ContainerHistoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Container history &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_ContainerHistoryMissing {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_ContainerHistoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current edition &apos;{0}&apos; found. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_CurrentEditionFound {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_CurrentEditionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current edition &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_CurrentEditionIsMissing {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_CurrentEditionIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity index &apos;{0}&apos; found. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_EntityIndexFound {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_EntityIndexFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity index &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_EntityIndexMissing {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_EntityIndexMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History document does not contain history element. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_HistoryElementNotFound {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_HistoryElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity index document does not contain the index element. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_IndexElementNotFound {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_IndexElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The master signature can not be verified. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_MasterSignatureCanNotBeVerified {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_MasterSignatureCanNotBeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No certificate found in current edition. Validation is canceled. ähnelt.
        /// </summary>
        internal static string Container_LoadAndValidate_NoCertificateFound {
            get {
                return ResourceManager.GetString("Container_LoadAndValidate_NoCertificateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One of the given predecessors does not exist. ähnelt.
        /// </summary>
        internal static string Container_NewEntity_ArgumentException_PredecessorDoesNotExist {
            get {
                return ResourceManager.GetString("Container_NewEntity_ArgumentException_PredecessorDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The container must be in the initialization or transformation phase to add a new entity. ähnelt.
        /// </summary>
        internal static string Container_NewEntity_InvalidOperation_WrongPhase {
            get {
                return ResourceManager.GetString("Container_NewEntity_InvalidOperation_WrongPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given label is allready in use. ähnelt.
        /// </summary>
        internal static string Container_NewEntity_LabelAllreadyInUse {
            get {
                return ResourceManager.GetString("Container_NewEntity_LabelAllreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum number of entities in the container is exceeded. ähnelt.
        /// </summary>
        internal static string Container_NewEntity_MaximumNumberExceeded {
            get {
                return ResourceManager.GetString("Container_NewEntity_MaximumNumberExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The container is invalid. ähnelt.
        /// </summary>
        internal static string Container_Open_ContainerInvalid {
            get {
                return ResourceManager.GetString("Container_Open_ContainerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The container is valid. Check the value signatures! ähnelt.
        /// </summary>
        internal static string Container_Open_ContainerIsValid {
            get {
                return ResourceManager.GetString("Container_Open_ContainerIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given path was not found:
        ///{0} ähnelt.
        /// </summary>
        internal static string Container_OpenContainer_ArgumentException_PathNotFound {
            get {
                return ResourceManager.GetString("Container_OpenContainer_ArgumentException_PathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reinstating the specified edition is impossible:
        ///{0} ähnelt.
        /// </summary>
        internal static string Container_ReinstateHistoryEdition_ReinstatingEditionImpossible {
            get {
                return ResourceManager.GetString("Container_ReinstateHistoryEdition_ReinstatingEditionImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The container must be in the transformation phase to remove an entity. ähnelt.
        /// </summary>
        internal static string Container_RemoveEntity_InvalidOperation_WrongPhase {
            get {
                return ResourceManager.GetString("Container_RemoveEntity_InvalidOperation_WrongPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while reading the XML document &apos;{0}&apos;: &apos;{1}&apos; ähnelt.
        /// </summary>
        internal static string Container_TryLoadXml_ErrorReadingXMLDocument {
            get {
                return ResourceManager.GetString("Container_TryLoadXml_ErrorReadingXMLDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy of signature for &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string Container_ValidateDoubleSignature_CopyOfSignatureIsMissing {
            get {
                return ResourceManager.GetString("Container_ValidateDoubleSignature_CopyOfSignatureIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy of signature for &apos;{0}&apos; does not match actual signature. ähnelt.
        /// </summary>
        internal static string Container_ValidateDoubleSignature_InvalidSignatureCopy {
            get {
                return ResourceManager.GetString("Container_ValidateDoubleSignature_InvalidSignatureCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature for &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string Container_ValidateDoubleSignature_SignatureIsMissing {
            get {
                return ResourceManager.GetString("Container_ValidateDoubleSignature_SignatureIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found the header of entity {0:00000}. ähnelt.
        /// </summary>
        internal static string Container_ValidateEntities_EntityHeaderFound {
            get {
                return ResourceManager.GetString("Container_ValidateEntities_EntityHeaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Header of the entity {0:00000} is missing. ähnelt.
        /// </summary>
        internal static string Container_ValidateEntities_EntityHeaderIsMissing {
            get {
                return ResourceManager.GetString("Container_ValidateEntities_EntityHeaderIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity label differs from index item: &apos;{0}&apos; not equal &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Container_ValidateEntities_EntityLabelDiffersFromIndexItem {
            get {
                return ResourceManager.GetString("Container_ValidateEntities_EntityLabelDiffersFromIndexItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XML Schema error in &apos;{0}&apos;: {1} ähnelt.
        /// </summary>
        internal static string Container_ValidateXml_SchemaError {
            get {
                return ResourceManager.GetString("Container_ValidateXml_SchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Validation of XML document &apos;{0}&apos; succeeded. ähnelt.
        /// </summary>
        internal static string Container_ValidateXml_XMLValid {
            get {
                return ResourceManager.GetString("Container_ValidateXml_XMLValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All entity values are integer and authentic. ähnelt.
        /// </summary>
        internal static string Container_VerifyEntityValueSignatures_AllEntityValuesIntegerAndAuthentic {
            get {
                return ResourceManager.GetString("Container_VerifyEntityValueSignatures_AllEntityValuesIntegerAndAuthentic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The integrity check is only allowed, if the container is sealed. ähnelt.
        /// </summary>
        internal static string Container_VerifyEntityValueSignatures_InvalidOperation_ContainerNotSealed {
            get {
                return ResourceManager.GetString("Container_VerifyEntityValueSignatures_InvalidOperation_ContainerNotSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xs:schema targetNamespace=&quot;http://www.mastersign.de/odec/container/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           xmlns=&quot;http://www.mastersign.de/odec/container/&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:sig=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///
        ///  &lt;xs:import namespace=&quot;http://www.w3.org/2000/09/xmldsig#&quot; /&gt;
        ///
        ///  &lt;xs:simpleType name=&quot;GUID&quot;&gt;
        ///    &lt;xs:annotation&gt;
        ///      &lt;xs:documentation&gt;
        ///        This is the format of a G [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ContainerSchema {
            get {
                return ResourceManager.GetString("ContainerSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File System Directory ähnelt.
        /// </summary>
        internal static string DirectoryStorage_Name {
            get {
                return ResourceManager.GetString("DirectoryStorage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The removing of the storage file failed. ähnelt.
        /// </summary>
        internal static string DirectoryStorage_Remove_StorageException_RemovingFailed {
            get {
                return ResourceManager.GetString("DirectoryStorage_Remove_StorageException_RemovingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given source file does not exist. ähnelt.
        /// </summary>
        internal static string DirectoryStorage_Write_SourceFileNotFound {
            get {
                return ResourceManager.GetString("DirectoryStorage_Write_SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writing of the storage file failed. ähnelt.
        /// </summary>
        internal static string DirectoryStorage_Write_StorageException_WritingFailed {
            get {
                return ResourceManager.GetString("DirectoryStorage_Write_StorageException_WritingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History signature in edition &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string EditionElement_Validate_HistorySignatureInEdition {
            get {
                return ResourceManager.GetString("EditionElement_Validate_HistorySignatureInEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GUID of edition &apos;{0}&apos; is empty. ähnelt.
        /// </summary>
        internal static string EditionElement_Validate_IdIsEmpty {
            get {
                return ResourceManager.GetString("EditionElement_Validate_IdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index signature in edition &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string EditionElement_Validate_IndexSignatureInEdition {
            get {
                return ResourceManager.GetString("EditionElement_Validate_IndexSignatureInEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History signature in edition &apos;{0}&apos; not set. ähnelt.
        /// </summary>
        internal static string EditionElement_Validate_NoHistorySignature {
            get {
                return ResourceManager.GetString("EditionElement_Validate_NoHistorySignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index signature in edition &apos;{0}&apos; not set. ähnelt.
        /// </summary>
        internal static string EditionElement_Validate_NoIndexSignature {
            get {
                return ResourceManager.GetString("EditionElement_Validate_NoIndexSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edition &apos;{0}&apos; has no owner. ähnelt.
        /// </summary>
        internal static string EditionElement_Validate_NoOwner {
            get {
                return ResourceManager.GetString("EditionElement_Validate_NoOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software field of edition &apos;{0}&apos; is empty. ähnelt.
        /// </summary>
        internal static string EditionElement_Validate_SoftwareFieldIsEmpty {
            get {
                return ResourceManager.GetString("EditionElement_Validate_SoftwareFieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given value name &apos;{0}&apos; is allready in use. ähnelt.
        /// </summary>
        internal static string Entity_AddValue_ArgumentException_NameAllreadyInUse {
            get {
                return ResourceManager.GetString("Entity_AddValue_ArgumentException_NameAllreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This entity is not open for changes. ähnelt.
        /// </summary>
        internal static string Entity_AddValue_InvalidOperation_NotOpenForChanges {
            get {
                return ResourceManager.GetString("Entity_AddValue_InvalidOperation_NotOpenForChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entity is allready closed. ähnelt.
        /// </summary>
        internal static string Entity_Close_InvalidOperation_EntityAllreadyClosed {
            get {
                return ResourceManager.GetString("Entity_Close_InvalidOperation_EntityAllreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This entity does not contain a provenance parameter set. ähnelt.
        /// </summary>
        internal static string Entity_GetProvenanceParameterSet_NoProvenanceParameterSet {
            get {
                return ResourceManager.GetString("Entity_GetProvenanceParameterSet_NoProvenanceParameterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No value with the given name &apos;{0}&apos; found. ähnelt.
        /// </summary>
        internal static string Entity_GetValue_ArgumentException_NameNotFound {
            get {
                return ResourceManager.GetString("Entity_GetValue_ArgumentException_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entity is not closed yet. ähnelt.
        /// </summary>
        internal static string Entity_RemoveFromStorage_InvalidOperation_EntityNotClosedYet {
            get {
                return ResourceManager.GetString("Entity_RemoveFromStorage_InvalidOperation_EntityNotClosedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given type ID is invalid. ähnelt.
        /// </summary>
        internal static string Entity_SetProvenanceParameterSet_ArgumentException_TypeIdInvalid {
            get {
                return ResourceManager.GetString("Entity_SetProvenanceParameterSet_ArgumentException_TypeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given value name &apos;{0}&apos; is allready in use. ähnelt.
        /// </summary>
        internal static string Entity_SetProvenanceParameterSet_InvalidOperation_ValueNameAllreadyInUse {
            get {
                return ResourceManager.GetString("Entity_SetProvenanceParameterSet_InvalidOperation_ValueNameAllreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given source file does not exist. ähnelt.
        /// </summary>
        internal static string Entity_SourceFileNotFound {
            get {
                return ResourceManager.GetString("Entity_SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of entity {0} is valid. ähnelt.
        /// </summary>
        internal static string Entity_ValidateStructure_StructureIsValid {
            get {
                return ResourceManager.GetString("Entity_ValidateStructure_StructureIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All value signatures in  the entity {0} are authentic. ähnelt.
        /// </summary>
        internal static string Entity_VerifyValueSignatures_AllValueSignaturesAuthentic {
            get {
                return ResourceManager.GetString("Entity_VerifyValueSignatures_AllValueSignaturesAuthentic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entity ID is less than 0 or greater than 99999. ähnelt.
        /// </summary>
        internal static string EntityElement_Validate_InvalidId {
            get {
                return ResourceManager.GetString("EntityElement_Validate_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provenance description in entity header {0} is invalid. ähnelt.
        /// </summary>
        internal static string EntityElement_Validate_InvalidProvenanceDescription {
            get {
                return ResourceManager.GetString("EntityElement_Validate_InvalidProvenanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provenance parameter set reference &apos;{0}&apos; in entity header {1} is invalid. ähnelt.
        /// </summary>
        internal static string EntityElement_Validate_InvalidProvenanceParameterSetReference {
            get {
                return ResourceManager.GetString("EntityElement_Validate_InvalidProvenanceParameterSetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of value reference &apos;{0}&apos; in entity header {1} is invalid. ähnelt.
        /// </summary>
        internal static string EntityElement_Validate_InvalidValueReference {
            get {
                return ResourceManager.GetString("EntityElement_Validate_InvalidValueReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entity {0:00000} does not contain any values. ähnelt.
        /// </summary>
        internal static string EntityElement_Validate_NoValues {
            get {
                return ResourceManager.GetString("EntityElement_Validate_NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of entity header {0} is valid. ähnelt.
        /// </summary>
        internal static string EntityElement_Validate_StructureIsValid {
            get {
                return ResourceManager.GetString("EntityElement_Validate_StructureIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data type mismatch at value &apos;{0}&apos; in entity &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string EntityType_ValidateEntity_DataTypeMismatch {
            get {
                return ResourceManager.GetString("EntityType_ValidateEntity_DataTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity type &apos;{0}&apos; of entity &apos;{1}&apos; is no valid output of its provenance &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string EntityType_ValidateEntity_ProvenanceMismatch {
            get {
                return ResourceManager.GetString("EntityType_ValidateEntity_ProvenanceMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required value &apos;{0}&apos; is missing in entity &apos;{1}&apos; of type &apos;{2}. ähnelt.
        /// </summary>
        internal static string EntityType_ValidateEntity_RequiredValueMissing {
            get {
                return ResourceManager.GetString("EntityType_ValidateEntity_RequiredValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value &apos;{0}&apos; in entity &apos;{1}&apos; is not part of type &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string EntityType_ValidateEntity_UnexpectedValue {
            get {
                return ResourceManager.GetString("EntityType_ValidateEntity_UnexpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provenance &apos;{0}&apos; of entity &apos;{1}&apos; is unknown. ähnelt.
        /// </summary>
        internal static string EntityType_ValidateEntity_UnknownProvenance {
            get {
                return ResourceManager.GetString("EntityType_ValidateEntity_UnknownProvenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity {0:00000} &apos;{1}&apos; is valid against its type &apos;{2}&apos;. ähnelt.
        /// </summary>
        internal static string EntityType_ValidateEntity_Valid {
            get {
                return ResourceManager.GetString("EntityType_ValidateEntity_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Stream.Null, if the data should be discarded. ähnelt.
        /// </summary>
        internal static string HashBuilder_ArgumentNullException_Target {
            get {
                return ResourceManager.GetString("HashBuilder_ArgumentNullException_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given stream is not writable. ähnelt.
        /// </summary>
        internal static string HashProvider_CreateHashBuilder_ArgumentException_StreamIsNotWritable {
            get {
                return ResourceManager.GetString("HashProvider_CreateHashBuilder_ArgumentException_StreamIsNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested hash algorithm is not supported. ähnelt.
        /// </summary>
        internal static string HashProvider_NotSupported_HashAlgorithm {
            get {
                return ResourceManager.GetString("HashProvider_NotSupported_HashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The history contains no items. ähnelt.
        /// </summary>
        internal static string HistoryElement_InvalidOperation_NoItems {
            get {
                return ResourceManager.GetString("HistoryElement_InvalidOperation_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History item {0} is invalid. ähnelt.
        /// </summary>
        internal static string HistoryElement_Validate_InvalidItem {
            get {
                return ResourceManager.GetString("HistoryElement_Validate_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of history is valid. ähnelt.
        /// </summary>
        internal static string HistoryElement_Validate_StructureIsValid {
            get {
                return ResourceManager.GetString("HistoryElement_Validate_StructureIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edition in history item &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string HistoryItemElement_Validate_EditionInHistoryItem {
            get {
                return ResourceManager.GetString("HistoryItemElement_Validate_EditionInHistoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edition in history item &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string HistoryItemElement_Validate_NoEdition {
            get {
                return ResourceManager.GetString("HistoryItemElement_Validate_NoEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Past master signature in history item &apos;{0}&apos; is missing&apos;. ähnelt.
        /// </summary>
        internal static string HistoryItemElement_Validate_NoPastMasterSignature {
            get {
                return ResourceManager.GetString("HistoryItemElement_Validate_NoPastMasterSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Past master signature in history item &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string HistoryItemElement_Validate_PastMasterSignatureInHistoryItem {
            get {
                return ResourceManager.GetString("HistoryItemElement_Validate_PastMasterSignatureInHistoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of history item &apos;{0}&apos; is valid. ähnelt.
        /// </summary>
        internal static string HistoryItemElement_Validate_ValidStructure {
            get {
                return ResourceManager.GetString("HistoryItemElement_Validate_ValidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The id of the given entity reference is invalid. ähnelt.
        /// </summary>
        internal static string IndexElement_Add_ArgumentException_InvalidEntityReference {
            get {
                return ResourceManager.GetString("IndexElement_Add_ArgumentException_InvalidEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No entity with id {0} in the index. ähnelt.
        /// </summary>
        internal static string IndexElement_ArgumentException_EntityIdNotFound {
            get {
                return ResourceManager.GetString("IndexElement_ArgumentException_EntityIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity index is empty. ähnelt.
        /// </summary>
        internal static string IndexElement_Validate_IndexIsEmpty {
            get {
                return ResourceManager.GetString("IndexElement_Validate_IndexIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index item &apos;{0}&apos; is invalid. ähnelt.
        /// </summary>
        internal static string IndexElement_Validate_IndexItemIsInvalid {
            get {
                return ResourceManager.GetString("IndexElement_Validate_IndexItemIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label of item &apos;{0}&apos; is used more than once. ähnelt.
        /// </summary>
        internal static string IndexElement_Validate_MultipleUseOfLabel {
            get {
                return ResourceManager.GetString("IndexElement_Validate_MultipleUseOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of entity index is valid. ähnelt.
        /// </summary>
        internal static string IndexElement_Validate_ValidStructure {
            get {
                return ResourceManager.GetString("IndexElement_Validate_ValidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity signature in index item &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string IndexItemElement_Validate_EntitySignatureInIndexItem {
            get {
                return ResourceManager.GetString("IndexItemElement_Validate_EntitySignatureInIndexItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID in index item is less or equal zero. ähnelt.
        /// </summary>
        internal static string IndexItemElement_Validate_InvalidId {
            get {
                return ResourceManager.GetString("IndexItemElement_Validate_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entity signature in index item &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string IndexItemElement_Validate_NoEntitySignature {
            get {
                return ResourceManager.GetString("IndexItemElement_Validate_NoEntitySignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of index item &apos;{0}&apos; is valid. ähnelt.
        /// </summary>
        internal static string IndexItemElement_Validate_ValidStructure {
            get {
                return ResourceManager.GetString("IndexItemElement_Validate_ValidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owner certificate is missing. ähnelt.
        /// </summary>
        internal static string Owner_Validate_NoCertificate {
            get {
                return ResourceManager.GetString("Owner_Validate_NoCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email field in owner is empty. ähnelt.
        /// </summary>
        internal static string Owner_Validate_NoEmail {
            get {
                return ResourceManager.GetString("Owner_Validate_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Institute field in owner is empty. ähnelt.
        /// </summary>
        internal static string Owner_Validate_NoInstitute {
            get {
                return ResourceManager.GetString("Owner_Validate_NoInstitute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operator field in owner is empty. ähnelt.
        /// </summary>
        internal static string Owner_Validate_NoOperator {
            get {
                return ResourceManager.GetString("Owner_Validate_NoOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of owner &apos;{0}&apos; is valid. ähnelt.
        /// </summary>
        internal static string Owner_Validate_ValidStructure {
            get {
                return ResourceManager.GetString("Owner_Validate_ValidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The profile is not schema conform:
        ///{0} ähnelt.
        /// </summary>
        internal static string Profile_LoadFromXml_FormatException_ProfileNotSchemaConform {
            get {
                return ResourceManager.GetString("Profile_LoadFromXml_FormatException_ProfileNotSchemaConform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given XML element is not in the expected namespace. ähnelt.
        /// </summary>
        internal static string Profile_LoadFromXml_WrongNamespace {
            get {
                return ResourceManager.GetString("Profile_LoadFromXml_WrongNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given XML element is not a Profile element. ähnelt.
        /// </summary>
        internal static string Profile_LoadFromXml_WrongXmlElement {
            get {
                return ResourceManager.GetString("Profile_LoadFromXml_WrongXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The profile of the container &apos;{0}&apos; does not match the validating profile &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Profile_ValidateContainer_ProfileMismatch {
            get {
                return ResourceManager.GetString("Profile_ValidateContainer_ProfileMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The profile version of the container &apos;{0}&apos; does not match the validating profile version &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Profile_ValidateContainer_ProfileVersionMismatch {
            get {
                return ResourceManager.GetString("Profile_ValidateContainer_ProfileVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type &apos;{0}&apos; of entity &apos;{1}&apos; is unknown. ähnelt.
        /// </summary>
        internal static string Profile_ValidateEntity_UnkownEntityType {
            get {
                return ResourceManager.GetString("Profile_ValidateEntity_UnkownEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xs:schema id=&quot;catalog&quot;
        ///           targetNamespace=&quot;http://www.mastersign.de/odec/profile/&quot;
        ///           elementFormDefault=&quot;qualified&quot;
        ///           xmlns=&quot;http://www.mastersign.de/odec/profile/&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;!-- ===== The Root Element ===== --&gt;
        ///
        ///  &lt;xs:element name=&quot;Profile&quot;&gt;
        ///    &lt;xs:annotation&gt;
        ///      &lt;xs:documentation&gt;
        ///        The container profile describes the process steps and interfaces for an automated fore [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ProfileSchema {
            get {
                return ResourceManager.GetString("ProfileSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The crypto provider has no access to the certificate. ähnelt.
        /// </summary>
        internal static string RSAProvider_NotSupported_NoCertificate {
            get {
                return ResourceManager.GetString("RSAProvider_NotSupported_NoCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This instance has no access to the private key. ähnelt.
        /// </summary>
        internal static string RSAProvider_NotSupported_NoPrivateKey {
            get {
                return ResourceManager.GetString("RSAProvider_NotSupported_NoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The verification of the certificate from &apos;{0}&apos; failed.
        ///{1} ähnelt.
        /// </summary>
        internal static string RSAProvider_ValidateCertificate_Failed {
            get {
                return ResourceManager.GetString("RSAProvider_ValidateCertificate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The verification of the certificate from &apos;{0}&apos; succeeded. ähnelt.
        /// </summary>
        internal static string RSAProvider_ValidateCertificate_Succeeded {
            get {
                return ResourceManager.GetString("RSAProvider_ValidateCertificate_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data source is not readable. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ArgumentException_SourceNotReadable {
            get {
                return ResourceManager.GetString("SignatureWrapper_ArgumentException_SourceNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given XML element does not contain a &apos;Signature&apos; child element. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ReadFromXml_NoSignatureElement {
            get {
                return ResourceManager.GetString("SignatureWrapper_ReadFromXml_NoSignatureElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signed info in the signature of &apos;{0}&apos; contains more than one data reference. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ValidateStructure_MoreThanOneDataReference {
            get {
                return ResourceManager.GetString("SignatureWrapper_ValidateStructure_MoreThanOneDataReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signed info in the signature of &apos;{0}&apos; contains no data reference. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ValidateStructure_NoDataReference {
            get {
                return ResourceManager.GetString("SignatureWrapper_ValidateStructure_NoDataReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature wrapper of &apos;{0}&apos; does not contain a signature. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ValidateStructure_NoSignature {
            get {
                return ResourceManager.GetString("SignatureWrapper_ValidateStructure_NoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature of &apos;{0}&apos; does not contain a signature value. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ValidateStructure_NoSignatureValue {
            get {
                return ResourceManager.GetString("SignatureWrapper_ValidateStructure_NoSignatureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature of &apos;{0}&apos; does not contain a signed info. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ValidateStructure_NoSignedInfo {
            get {
                return ResourceManager.GetString("SignatureWrapper_ValidateStructure_NoSignedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of signature of &apos;{0}&apos; is valid. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_ValidateStructure_ValidStructure {
            get {
                return ResourceManager.GetString("SignatureWrapper_ValidateStructure_ValidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data of &apos;{0}&apos; is intact. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifyDigest_DataIsInteger {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifyDigest_DataIsInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data of &apos;{0}&apos; was altered. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifyDigest_DataNotInteger {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifyDigest_DataNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The digest algorithm used in the signature is not supported. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifyDigest_DigestAlgorithmNotSupported {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifyDigest_DigestAlgorithmNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URI in signature of &apos;{0}&apos; does not match the given URI. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifyDigest_UriMismatch {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifyDigest_UriMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Canonicalizer &apos;{0}&apos; used in the XML signature &apos;{1}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifySignature_CanonicalizerNotSupported {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifySignature_CanonicalizerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature algorithm &apos;{0}&apos; used in the XML signature &apos;{1}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifySignature_SignatureAlgorithmNotSupported {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifySignature_SignatureAlgorithmNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature of &apos;{0}&apos; is authentic. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifySignature_SignatureIsAuthentic {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifySignature_SignatureIsAuthentic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature of &apos;{0}&apos; is not authentic. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_VerifySignature_SignatureNotAuthentic {
            get {
                return ResourceManager.GetString("SignatureWrapper_VerifySignature_SignatureNotAuthentic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no Signature set. ähnelt.
        /// </summary>
        internal static string SignatureWrapper_WriteToXml_InvalidOperation_NoSignature {
            get {
                return ResourceManager.GetString("SignatureWrapper_WriteToXml_InvalidOperation_NoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given path is empty. ähnelt.
        /// </summary>
        internal static string Storage_ArgumentException_EmptyPath {
            get {
                return ResourceManager.GetString("Storage_ArgumentException_EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The opening of the storage file for reading failed. ähnelt.
        /// </summary>
        internal static string Storage_Read_OpeningFailed {
            get {
                return ResourceManager.GetString("Storage_Read_OpeningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The storage file, specified by the given relative path was not found. ähnelt.
        /// </summary>
        internal static string Storage_StorageFileNotFound {
            get {
                return ResourceManager.GetString("Storage_StorageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given stream is not readable. ähnelt.
        /// </summary>
        internal static string Storage_Write_StreamNotReadable {
            get {
                return ResourceManager.GetString("Storage_Write_StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unlabeled ähnelt.
        /// </summary>
        internal static string Unlabeled {
            get {
                return ResourceManager.GetString("Unlabeled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value is not stored yet. ähnelt.
        /// </summary>
        internal static string Value_InvalidOperation_ValueNotStoredYet {
            get {
                return ResourceManager.GetString("Value_InvalidOperation_ValueNotStoredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value appearance is suppressed. ähnelt.
        /// </summary>
        internal static string Value_Read_InvalidOperation_ValueAppearanceIsSuppressed {
            get {
                return ResourceManager.GetString("Value_Read_InvalidOperation_ValueAppearanceIsSuppressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Signature of &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string Value_ValidateStructure_SignatureMissing {
            get {
                return ResourceManager.GetString("Value_ValidateStructure_SignatureMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure of &apos;{0}&apos; is valid. ähnelt.
        /// </summary>
        internal static string Value_ValidateStructure_StructureIsValid {
            get {
                return ResourceManager.GetString("Value_ValidateStructure_StructureIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value data file &apos;{0}&apos; is missing. ähnelt.
        /// </summary>
        internal static string Value_ValidateStructure_ValueFileMissing {
            get {
                return ResourceManager.GetString("Value_ValidateStructure_ValueFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value data file &apos;{0}&apos; is present but its appearance is marked as &apos;suppressed&apos;. ähnelt.
        /// </summary>
        internal static string Value_ValidateStructure_ValueFileNotExpected {
            get {
                return ResourceManager.GetString("Value_ValidateStructure_ValueFileNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No source file was given to the constructor. ähnelt.
        /// </summary>
        internal static string Value_WriteAndSignValue_InvalidOperation_NoSourceFileGiven {
            get {
                return ResourceManager.GetString("Value_WriteAndSignValue_InvalidOperation_NoSourceFileGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value is allready stored. ähnelt.
        /// </summary>
        internal static string Value_WriteAndSignValue_InvalidOperation_ValueAllreadyStored {
            get {
                return ResourceManager.GetString("Value_WriteAndSignValue_InvalidOperation_ValueAllreadyStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///&lt;!DOCTYPE schema
        ///  PUBLIC &quot;-//W3C//DTD XMLSchema 200102//EN&quot; &quot;http://www.w3.org/2001/XMLSchema.dtd&quot;
        /// [
        ///   &lt;!ATTLIST schema 
        ///     xmlns:ds CDATA #FIXED &quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///   &lt;!ENTITY dsig &apos;http://www.w3.org/2000/09/xmldsig#&apos;&gt;
        ///   &lt;!ENTITY % p &apos;&apos;&gt;
        ///   &lt;!ENTITY % s &apos;&apos;&gt;
        ///  ]&gt;
        ///--&gt;
        ///&lt;!-- Schema for XML Signatures
        ///    http://www.w3.org/2000/09/xmldsig#
        ///    $Revision: 1.1 $ on $Date: 2002/02/08 20:32:26 $ by $Author: reagle $
        ///
        ///    Copyright  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string XmldsigCoreSchema {
            get {
                return ResourceManager.GetString("XmldsigCoreSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This instance is invalid. ähnelt.
        /// </summary>
        internal static string XmlStorable_WriteToXml_ThisInstanceIsInvalid {
            get {
                return ResourceManager.GetString("XmlStorable_WriteToXml_ThisInstanceIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The given name is empty. ähnelt.
        /// </summary>
        internal static string XmlUtils_ReadParsedObject_ArgumentException_NameIsEmpty {
            get {
                return ResourceManager.GetString("XmlUtils_ReadParsedObject_ArgumentException_NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified path contains invalid characters. ähnelt.
        /// </summary>
        internal static string ZipStorage_ArgumentException_InvalidPathCharacters {
            get {
                return ResourceManager.GetString("ZipStorage_ArgumentException_InvalidPathCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZIP-File ähnelt.
        /// </summary>
        internal static string ZipStorage_Name {
            get {
                return ResourceManager.GetString("ZipStorage_Name", resourceCulture);
            }
        }
    }
}
